Document: fcamera
Title: Debian fcamera Manual
Author: <insert document author here>
Abstract: This manual describes what fcamera is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fcamera/fcamera.sgml.gz

Format: postscript
Files: /usr/share/doc/fcamera/fcamera.ps.gz

Format: text
Files: /usr/share/doc/fcamera/fcamera.text.gz

Format: HTML
Index: /usr/share/doc/fcamera/html/index.html
Files: /usr/share/doc/fcamera/html/*.html


