Document: fcam
Title: Debian fcam Manual
Author: <insert document author here>
Abstract: This manual describes what fcam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fcam/fcam.sgml.gz

Format: postscript
Files: /usr/share/doc/fcam/fcam.ps.gz

Format: text
Files: /usr/share/doc/fcam/fcam.text.gz

Format: HTML
Index: /usr/share/doc/fcam/html/index.html
Files: /usr/share/doc/fcam/html/*.html


