// Generated by the protocol buffer compiler.  DO NOT EDIT!

package camsync.server;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage {
    // Use Msg.newBuilder() to construct.
    private Msg() {}
    
    private static final Msg defaultInstance = new Msg();
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }
    
    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return camsync.server.Messages.internal_static_Msg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return camsync.server.Messages.internal_static_Msg_fieldAccessorTable;
    }
    
    public static final class Image extends
        com.google.protobuf.GeneratedMessage {
      // Use Image.newBuilder() to construct.
      private Image() {}
      
      private static final Image defaultInstance = new Image();
      public static Image getDefaultInstance() {
        return defaultInstance;
      }
      
      public Image getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return camsync.server.Messages.internal_static_Msg_Image_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return camsync.server.Messages.internal_static_Msg_Image_fieldAccessorTable;
      }
      
      // optional bytes uuid = 1;
      public static final int UUID_FIELD_NUMBER = 1;
      private boolean hasUuid;
      private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasUuid() { return hasUuid; }
      public com.google.protobuf.ByteString getUuid() { return uuid_; }
      
      // optional bytes data = 2;
      public static final int DATA_FIELD_NUMBER = 2;
      private boolean hasData;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() { return hasData; }
      public com.google.protobuf.ByteString getData() { return data_; }
      
      // optional float lat = 3;
      public static final int LAT_FIELD_NUMBER = 3;
      private boolean hasLat;
      private float lat_ = 0F;
      public boolean hasLat() { return hasLat; }
      public float getLat() { return lat_; }
      
      // optional float long = 4;
      public static final int LONG_FIELD_NUMBER = 4;
      private boolean hasLong;
      private float long_ = 0F;
      public boolean hasLong() { return hasLong; }
      public float getLong() { return long_; }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasUuid()) {
          output.writeBytes(1, getUuid());
        }
        if (hasData()) {
          output.writeBytes(2, getData());
        }
        if (hasLat()) {
          output.writeFloat(3, getLat());
        }
        if (hasLong()) {
          output.writeFloat(4, getLong());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasUuid()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getUuid());
        }
        if (hasData()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getData());
        }
        if (hasLat()) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, getLat());
        }
        if (hasLong()) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(4, getLong());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static camsync.server.Messages.Msg.Image parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static camsync.server.Messages.Msg.Image parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static camsync.server.Messages.Msg.Image parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static camsync.server.Messages.Msg.Image parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static camsync.server.Messages.Msg.Image parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static camsync.server.Messages.Msg.Image parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static camsync.server.Messages.Msg.Image parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static camsync.server.Messages.Msg.Image parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static camsync.server.Messages.Msg.Image parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static camsync.server.Messages.Msg.Image parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(camsync.server.Messages.Msg.Image prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private camsync.server.Messages.Msg.Image result;
        
        // Construct using camsync.server.Messages.Msg.Image.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new camsync.server.Messages.Msg.Image();
          return builder;
        }
        
        protected camsync.server.Messages.Msg.Image internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new camsync.server.Messages.Msg.Image();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return camsync.server.Messages.Msg.Image.getDescriptor();
        }
        
        public camsync.server.Messages.Msg.Image getDefaultInstanceForType() {
          return camsync.server.Messages.Msg.Image.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public camsync.server.Messages.Msg.Image build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private camsync.server.Messages.Msg.Image buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public camsync.server.Messages.Msg.Image buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          camsync.server.Messages.Msg.Image returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof camsync.server.Messages.Msg.Image) {
            return mergeFrom((camsync.server.Messages.Msg.Image)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(camsync.server.Messages.Msg.Image other) {
          if (other == camsync.server.Messages.Msg.Image.getDefaultInstance()) return this;
          if (other.hasUuid()) {
            setUuid(other.getUuid());
          }
          if (other.hasData()) {
            setData(other.getData());
          }
          if (other.hasLat()) {
            setLat(other.getLat());
          }
          if (other.hasLong()) {
            setLong(other.getLong());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setUuid(input.readBytes());
                break;
              }
              case 18: {
                setData(input.readBytes());
                break;
              }
              case 29: {
                setLat(input.readFloat());
                break;
              }
              case 37: {
                setLong(input.readFloat());
                break;
              }
            }
          }
        }
        
        
        // optional bytes uuid = 1;
        public boolean hasUuid() {
          return result.hasUuid();
        }
        public com.google.protobuf.ByteString getUuid() {
          return result.getUuid();
        }
        public Builder setUuid(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasUuid = true;
          result.uuid_ = value;
          return this;
        }
        public Builder clearUuid() {
          result.hasUuid = false;
          result.uuid_ = getDefaultInstance().getUuid();
          return this;
        }
        
        // optional bytes data = 2;
        public boolean hasData() {
          return result.hasData();
        }
        public com.google.protobuf.ByteString getData() {
          return result.getData();
        }
        public Builder setData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasData = true;
          result.data_ = value;
          return this;
        }
        public Builder clearData() {
          result.hasData = false;
          result.data_ = getDefaultInstance().getData();
          return this;
        }
        
        // optional float lat = 3;
        public boolean hasLat() {
          return result.hasLat();
        }
        public float getLat() {
          return result.getLat();
        }
        public Builder setLat(float value) {
          result.hasLat = true;
          result.lat_ = value;
          return this;
        }
        public Builder clearLat() {
          result.hasLat = false;
          result.lat_ = 0F;
          return this;
        }
        
        // optional float long = 4;
        public boolean hasLong() {
          return result.hasLong();
        }
        public float getLong() {
          return result.getLong();
        }
        public Builder setLong(float value) {
          result.hasLong = true;
          result.long_ = value;
          return this;
        }
        public Builder clearLong() {
          result.hasLong = false;
          result.long_ = 0F;
          return this;
        }
      }
      
      static {
        camsync.server.Messages.getDescriptor();
      }
      
      static {
        camsync.server.Messages.internalForceInit();
      }
    }
    
    public static final class Command extends
        com.google.protobuf.GeneratedMessage {
      // Use Command.newBuilder() to construct.
      private Command() {}
      
      private static final Command defaultInstance = new Command();
      public static Command getDefaultInstance() {
        return defaultInstance;
      }
      
      public Command getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return camsync.server.Messages.internal_static_Msg_Command_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return camsync.server.Messages.internal_static_Msg_Command_fieldAccessorTable;
      }
      
      // required bytes uuid = 1;
      public static final int UUID_FIELD_NUMBER = 1;
      private boolean hasUuid;
      private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasUuid() { return hasUuid; }
      public com.google.protobuf.ByteString getUuid() { return uuid_; }
      
      // optional bool image = 2;
      public static final int IMAGE_FIELD_NUMBER = 2;
      private boolean hasImage;
      private boolean image_ = false;
      public boolean hasImage() { return hasImage; }
      public boolean getImage() { return image_; }
      
      // optional bool flash = 3;
      public static final int FLASH_FIELD_NUMBER = 3;
      private boolean hasFlash;
      private boolean flash_ = false;
      public boolean hasFlash() { return hasFlash; }
      public boolean getFlash() { return flash_; }
      
      // optional int32 exposure = 4;
      public static final int EXPOSURE_FIELD_NUMBER = 4;
      private boolean hasExposure;
      private int exposure_ = 0;
      public boolean hasExposure() { return hasExposure; }
      public int getExposure() { return exposure_; }
      
      public final boolean isInitialized() {
        if (!hasUuid) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasUuid()) {
          output.writeBytes(1, getUuid());
        }
        if (hasImage()) {
          output.writeBool(2, getImage());
        }
        if (hasFlash()) {
          output.writeBool(3, getFlash());
        }
        if (hasExposure()) {
          output.writeInt32(4, getExposure());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasUuid()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getUuid());
        }
        if (hasImage()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(2, getImage());
        }
        if (hasFlash()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, getFlash());
        }
        if (hasExposure()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, getExposure());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static camsync.server.Messages.Msg.Command parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static camsync.server.Messages.Msg.Command parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static camsync.server.Messages.Msg.Command parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static camsync.server.Messages.Msg.Command parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static camsync.server.Messages.Msg.Command parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static camsync.server.Messages.Msg.Command parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static camsync.server.Messages.Msg.Command parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static camsync.server.Messages.Msg.Command parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static camsync.server.Messages.Msg.Command parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static camsync.server.Messages.Msg.Command parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(camsync.server.Messages.Msg.Command prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private camsync.server.Messages.Msg.Command result;
        
        // Construct using camsync.server.Messages.Msg.Command.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new camsync.server.Messages.Msg.Command();
          return builder;
        }
        
        protected camsync.server.Messages.Msg.Command internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new camsync.server.Messages.Msg.Command();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return camsync.server.Messages.Msg.Command.getDescriptor();
        }
        
        public camsync.server.Messages.Msg.Command getDefaultInstanceForType() {
          return camsync.server.Messages.Msg.Command.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public camsync.server.Messages.Msg.Command build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private camsync.server.Messages.Msg.Command buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public camsync.server.Messages.Msg.Command buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          camsync.server.Messages.Msg.Command returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof camsync.server.Messages.Msg.Command) {
            return mergeFrom((camsync.server.Messages.Msg.Command)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(camsync.server.Messages.Msg.Command other) {
          if (other == camsync.server.Messages.Msg.Command.getDefaultInstance()) return this;
          if (other.hasUuid()) {
            setUuid(other.getUuid());
          }
          if (other.hasImage()) {
            setImage(other.getImage());
          }
          if (other.hasFlash()) {
            setFlash(other.getFlash());
          }
          if (other.hasExposure()) {
            setExposure(other.getExposure());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setUuid(input.readBytes());
                break;
              }
              case 16: {
                setImage(input.readBool());
                break;
              }
              case 24: {
                setFlash(input.readBool());
                break;
              }
              case 32: {
                setExposure(input.readInt32());
                break;
              }
            }
          }
        }
        
        
        // required bytes uuid = 1;
        public boolean hasUuid() {
          return result.hasUuid();
        }
        public com.google.protobuf.ByteString getUuid() {
          return result.getUuid();
        }
        public Builder setUuid(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasUuid = true;
          result.uuid_ = value;
          return this;
        }
        public Builder clearUuid() {
          result.hasUuid = false;
          result.uuid_ = getDefaultInstance().getUuid();
          return this;
        }
        
        // optional bool image = 2;
        public boolean hasImage() {
          return result.hasImage();
        }
        public boolean getImage() {
          return result.getImage();
        }
        public Builder setImage(boolean value) {
          result.hasImage = true;
          result.image_ = value;
          return this;
        }
        public Builder clearImage() {
          result.hasImage = false;
          result.image_ = false;
          return this;
        }
        
        // optional bool flash = 3;
        public boolean hasFlash() {
          return result.hasFlash();
        }
        public boolean getFlash() {
          return result.getFlash();
        }
        public Builder setFlash(boolean value) {
          result.hasFlash = true;
          result.flash_ = value;
          return this;
        }
        public Builder clearFlash() {
          result.hasFlash = false;
          result.flash_ = false;
          return this;
        }
        
        // optional int32 exposure = 4;
        public boolean hasExposure() {
          return result.hasExposure();
        }
        public int getExposure() {
          return result.getExposure();
        }
        public Builder setExposure(int value) {
          result.hasExposure = true;
          result.exposure_ = value;
          return this;
        }
        public Builder clearExposure() {
          result.hasExposure = false;
          result.exposure_ = 0;
          return this;
        }
      }
      
      static {
        camsync.server.Messages.getDescriptor();
      }
      
      static {
        camsync.server.Messages.internalForceInit();
      }
    }
    
    // optional .Msg.Image image = 1;
    public static final int IMAGE_FIELD_NUMBER = 1;
    private boolean hasImage;
    private camsync.server.Messages.Msg.Image image_ = camsync.server.Messages.Msg.Image.getDefaultInstance();
    public boolean hasImage() { return hasImage; }
    public camsync.server.Messages.Msg.Image getImage() { return image_; }
    
    // optional .Msg.Command command = 2;
    public static final int COMMAND_FIELD_NUMBER = 2;
    private boolean hasCommand;
    private camsync.server.Messages.Msg.Command command_ = camsync.server.Messages.Msg.Command.getDefaultInstance();
    public boolean hasCommand() { return hasCommand; }
    public camsync.server.Messages.Msg.Command getCommand() { return command_; }
    
    public final boolean isInitialized() {
      if (hasCommand()) {
        if (!getCommand().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasImage()) {
        output.writeMessage(1, getImage());
      }
      if (hasCommand()) {
        output.writeMessage(2, getCommand());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasImage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getImage());
      }
      if (hasCommand()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCommand());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static camsync.server.Messages.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static camsync.server.Messages.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static camsync.server.Messages.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static camsync.server.Messages.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static camsync.server.Messages.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static camsync.server.Messages.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static camsync.server.Messages.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static camsync.server.Messages.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static camsync.server.Messages.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static camsync.server.Messages.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(camsync.server.Messages.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private camsync.server.Messages.Msg result;
      
      // Construct using camsync.server.Messages.Msg.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new camsync.server.Messages.Msg();
        return builder;
      }
      
      protected camsync.server.Messages.Msg internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new camsync.server.Messages.Msg();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return camsync.server.Messages.Msg.getDescriptor();
      }
      
      public camsync.server.Messages.Msg getDefaultInstanceForType() {
        return camsync.server.Messages.Msg.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public camsync.server.Messages.Msg build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private camsync.server.Messages.Msg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public camsync.server.Messages.Msg buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        camsync.server.Messages.Msg returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof camsync.server.Messages.Msg) {
          return mergeFrom((camsync.server.Messages.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(camsync.server.Messages.Msg other) {
        if (other == camsync.server.Messages.Msg.getDefaultInstance()) return this;
        if (other.hasImage()) {
          mergeImage(other.getImage());
        }
        if (other.hasCommand()) {
          mergeCommand(other.getCommand());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              camsync.server.Messages.Msg.Image.Builder subBuilder = camsync.server.Messages.Msg.Image.newBuilder();
              if (hasImage()) {
                subBuilder.mergeFrom(getImage());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setImage(subBuilder.buildPartial());
              break;
            }
            case 18: {
              camsync.server.Messages.Msg.Command.Builder subBuilder = camsync.server.Messages.Msg.Command.newBuilder();
              if (hasCommand()) {
                subBuilder.mergeFrom(getCommand());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommand(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .Msg.Image image = 1;
      public boolean hasImage() {
        return result.hasImage();
      }
      public camsync.server.Messages.Msg.Image getImage() {
        return result.getImage();
      }
      public Builder setImage(camsync.server.Messages.Msg.Image value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasImage = true;
        result.image_ = value;
        return this;
      }
      public Builder setImage(camsync.server.Messages.Msg.Image.Builder builderForValue) {
        result.hasImage = true;
        result.image_ = builderForValue.build();
        return this;
      }
      public Builder mergeImage(camsync.server.Messages.Msg.Image value) {
        if (result.hasImage() &&
            result.image_ != camsync.server.Messages.Msg.Image.getDefaultInstance()) {
          result.image_ =
            camsync.server.Messages.Msg.Image.newBuilder(result.image_).mergeFrom(value).buildPartial();
        } else {
          result.image_ = value;
        }
        result.hasImage = true;
        return this;
      }
      public Builder clearImage() {
        result.hasImage = false;
        result.image_ = camsync.server.Messages.Msg.Image.getDefaultInstance();
        return this;
      }
      
      // optional .Msg.Command command = 2;
      public boolean hasCommand() {
        return result.hasCommand();
      }
      public camsync.server.Messages.Msg.Command getCommand() {
        return result.getCommand();
      }
      public Builder setCommand(camsync.server.Messages.Msg.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCommand = true;
        result.command_ = value;
        return this;
      }
      public Builder setCommand(camsync.server.Messages.Msg.Command.Builder builderForValue) {
        result.hasCommand = true;
        result.command_ = builderForValue.build();
        return this;
      }
      public Builder mergeCommand(camsync.server.Messages.Msg.Command value) {
        if (result.hasCommand() &&
            result.command_ != camsync.server.Messages.Msg.Command.getDefaultInstance()) {
          result.command_ =
            camsync.server.Messages.Msg.Command.newBuilder(result.command_).mergeFrom(value).buildPartial();
        } else {
          result.command_ = value;
        }
        result.hasCommand = true;
        return this;
      }
      public Builder clearCommand() {
        result.hasCommand = false;
        result.command_ = camsync.server.Messages.Msg.Command.getDefaultInstance();
        return this;
      }
    }
    
    static {
      camsync.server.Messages.getDescriptor();
    }
    
    static {
      camsync.server.Messages.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_Image_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_Image_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_Command_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/camsync/server/messages.proto\"\310\001\n\003" +
      "Msg\022\031\n\005image\030\001 \001(\0132\n.Msg.Image\022\035\n\007comman" +
      "d\030\002 \001(\0132\014.Msg.Command\032>\n\005Image\022\014\n\004uuid\030\001" +
      " \001(\014\022\014\n\004data\030\002 \001(\014\022\013\n\003lat\030\003 \001(\002\022\014\n\004long\030" +
      "\004 \001(\002\032G\n\007Command\022\014\n\004uuid\030\001 \002(\014\022\r\n\005image\030" +
      "\002 \001(\010\022\r\n\005flash\030\003 \001(\010\022\020\n\010exposure\030\004 \001(\005B\020" +
      "\n\016camsync.server"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_descriptor,
              new java.lang.String[] { "Image", "Command", },
              camsync.server.Messages.Msg.class,
              camsync.server.Messages.Msg.Builder.class);
          internal_static_Msg_Image_descriptor =
            internal_static_Msg_descriptor.getNestedTypes().get(0);
          internal_static_Msg_Image_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_Image_descriptor,
              new java.lang.String[] { "Uuid", "Data", "Lat", "Long", },
              camsync.server.Messages.Msg.Image.class,
              camsync.server.Messages.Msg.Image.Builder.class);
          internal_static_Msg_Command_descriptor =
            internal_static_Msg_descriptor.getNestedTypes().get(1);
          internal_static_Msg_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Msg_Command_descriptor,
              new java.lang.String[] { "Uuid", "Image", "Flash", "Exposure", },
              camsync.server.Messages.Msg.Command.class,
              camsync.server.Messages.Msg.Command.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
